version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: family_tree
    environment:
      POSTGRES_USER: family_tree
      POSTGRES_PASSWORD: family_tree
      POSTGRES_DB: family_tree
    ports:
      - "5433:5432"  # mapowanie portów, host 5433 -> kontener 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: