BEGIN;

DROP TABLE IF EXISTS osoby CASCADE;
DROP TABLE IF EXISTS relacje_symetryczne CASCADE;
DROP TABLE IF EXISTS relacje_niesymetryczne CASCADE;
DROP TABLE IF EXISTS typy_rs CASCADE;
DROP TABLE IF EXISTS typy_rns CASCADE;
DROP TABLE IF EXISTS miejsca CASCADE;
DROP TABLE IF EXISTS typy_miejsc CASCADE;
DROP TABLE IF EXISTS uwagi_osoby CASCADE;
DROP TABLE IF EXISTS uwagi CASCADE;
DROP TABLE IF EXISTS typy_uwag CASCADE;
DROP TABLE IF EXISTS zawody CASCADE;
DROP TABLE IF EXISTS zawody_osoby CASCADE;
DROP TABLE IF EXISTS miejsce_pracy CASCADE;
DROP TABLE IF EXISTS tytuly CASCADE;
DROP TABLE IF EXISTS tytuly_osoby CASCADE;
DROP TABLE IF EXISTS grupy CASCADE;
DROP TABLE IF EXISTS grupy_osoby CASCADE;
DROP TABLE IF EXISTS uwagi_grupy CASCADE;
DROP TABLE IF EXISTS nazwiska CASCADE;

DROP SEQUENCE IF EXISTS nazwiska_kolejnosc_seq CASCADE;

DROP FUNCTION IF EXISTS date_check(d custom_date) CASCADE;
DROP FUNCTION IF EXISTS date_comp(a custom_date, b custom_date) CASCADE;

DROP FUNCTION IF EXISTS check_if_ancestor(child OSOBY, ancestor OSOBY) CASCADE;
DROP FUNCTION IF EXISTS check_if_ancestor_update() CASCADE;
DROP TRIGGER IF EXISTS dobry_poset ON osoby CASCADE;
DROP FUNCTION IF EXISTS check_if_nadtytul(child tytuly, ancestor tytuly) CASCADE;
DROP FUNCTION IF EXISTS check_if_nadtytul_update() CASCADE;
DROP TRIGGER IF EXISTS dobry_poset_tytuly ON tytuly CASCADE;

DROP VIEW IF EXISTS praca CASCADE;
DROP VIEW IF EXISTS osoby_nazwiska;

DROP FUNCTION IF EXISTS dni_w_miesiacu;
DROP FUNCTION IF EXISTS czy_rok_przestepny;

DROP TYPE IF EXISTS custom_date CASCADE;

COMMIT;
