BEGIN;

DROP TABLE IF EXISTS osoby CASCADE;
DROP TABLE IF EXISTS relacje_symetryczne CASCADE;
DROP TABLE IF EXISTS relacje_niesymetryczne CASCADE;
DROP TABLE IF EXISTS typy_rs CASCADE;
DROP TABLE IF EXISTS typy_rns CASCADE;
DROP TABLE IF EXISTS miejsca CASCADE;
DROP TABLE IF EXISTS typy_miejsc CASCADE;
DROP TABLE IF EXISTS uwagi_osoby CASCADE;
DROP TABLE IF EXISTS uwagi CASCADE;
DROP TABLE IF EXISTS typy_uwag CASCADE;
DROP TABLE IF EXISTS zawody CASCADE;
DROP TABLE IF EXISTS zawody_osoby CASCADE;
DROP TABLE IF EXISTS miejsce_pracy CASCADE;
DROP TABLE IF EXISTS tytuly CASCADE;
DROP TABLE IF EXISTS tytuly_osoby CASCADE;
DROP TABLE IF EXISTS grupy CASCADE;
DROP TABLE IF EXISTS grupy_osoby CASCADE;
DROP TABLE IF EXISTS uwagi_grupy CASCADE;
DROP TABLE IF EXISTS daty CASCADE;
DROP TABLE IF EXISTS nazwiska CASCADE;

DROP SEQUENCE IF EXISTS nazwiska_kolejnosc_seq;

DROP FUNCTION IF EXISTS dni_w_miesiacu;
DROP FUNCTION IF EXISTS czy_rok_przestepny;

COMMIT;